--- START OF FILE admin/config.yml ---
backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content.json"
        label: "Page d'Accueil"
        name: "home"
        fields:
          - { label: "Métadonnées (SEO)", name: "meta", widget: "object", fields: [
              { label: "Titre de la page", name: "title", widget: "string" },
              { label: "Description de la page", name: "description", widget: "text" },
              { label: "Favicon 32x32", name: "favicon_32", widget: "image" },
              { label: "Favicon 192x192", name: "favicon_192", widget: "image" },
              { label: "Icône Apple Touch", name: "apple_touch_icon", widget: "image" },
              { label: "Couleur du thème (mobile)", name: "theme_color", widget: "string" }
            ]}
          - { label: "Navigation", name: "navigation", widget: "object", fields: [
              { label: "Logo", name: "logo", widget: "image" },
              { label: "Texte alternatif du logo", name: "logo_alt", widget: "string" },
              { label: "Texte pour lecteur d'écran (logo)", name: "logo_sr_text", widget: "string" },
              { label: "Liens du menu", name: "links", widget: "list", fields: [
                  { label: "Texte", name: "label", widget: "string" },
                  { label: "Ancre (ex: #services)", name: "href", widget: "string" }
                ]},
              { label: "Bouton d'action", name: "cta", widget: "object", fields: [
                  { label: "Texte", name: "label", widget: "string" },
                  { label: "Ancre", name: "href", widget: "string" }
                ]}
            ]}
          - { label: "Section Héros", name: "hero", widget: "object", fields: [
              { label: "Image de fond", name: "background_image", widget: "image" },
              { label: "Texte alternatif de l'image", name: "background_alt", widget: "string" },
              { label: "Titre (partie 1)", name: "title_part1", widget: "string" },
              { label: "Titre (partie surlignée)", name: "title_highlight", widget: "string" },
              { label: "Sous-titre", name: "subtitle", widget: "text" },
              { label: "Bouton d'action 1", name: "cta1", widget: "object", fields: [
                  { label: "Texte", name: "label", widget: "string" },
                  { label: "Ancre", name: "href", widget: "string" }
                ]},
              { label: "Bouton d'action 2", name: "cta2", widget: "object", fields: [
                  { label: "Texte", name: "label", widget: "string" },
                  { label: "Ancre", name: "href", widget: "string" }
                ]}
            ]}
          - { label: "Section Réalisations", name: "realisations", widget: "object", fields: [
              { label: "Titre", name: "title", widget: "string" },
              { label: "Titre (partie surlignée)", name: "title_highlight", widget: "string" },
              { label: "Projets", name: "projects", widget: "list", fields: [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Texte alternatif", name: "alt", widget: "string" },
                  { label: "Légende", name: "caption", widget: "string" }
                ]}
            ]}
          - { label: "Section Services", name: "services", widget: "object", fields: [
              { label: "Titre", name: "title", widget: "string" },
              { label: "Titre (partie surlignée)", name: "title_highlight", widget: "string" },
              { label: "Cartes de service", name: "cards", widget: "list", fields: [
                  { label: "Icône (code SVG)", name: "icon_svg", widget: "text" },
                  { label: "Titre", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "text" },
                  { label: "Étiquette (prix, etc.)", name: "tag_text", widget: "string" },
                  { label: "Texte du lien", name: "link_label", widget: "string" },
                  { label: "Ancre du lien", name: "link_href", widget: "string" },
                  { label: "Mettre en avant (populaire) ?", name: "is_popular", widget: "boolean", default: false }
                ]}
            ]}
          - { label: "Section À Propos", name: "about", widget: "object", fields: [
              { label: "Titre", name: "title", widget: "string" },
              { label: "Titre (partie surlignée)", name: "title_highlight", widget: "string" },
              { label: "Paragraphes", name: "paragraphs", widget: "list", fields: [
                  { label: "Paragraphe", name: "text", widget: "text" }
                ]},
              { label: "Bouton d'action 1", name: "cta1", widget: "object", fields: [
                  { label: "Texte", name: "label", widget: "string" },
                  { label: "Ancre", name: "href", widget: "string" }
                ]},
              { label: "Bouton d'action 2", name: "cta2", widget: "object", fields: [
                  { label: "Texte", name: "label", widget: "string" },
                  { label: "Ancre", name: "href", widget: "string" }
                ]},
              { label: "Image portrait", name: "image", widget: "image" },
              { label: "Texte alternatif de l'image", name: "image_alt", widget: "string" }
            ]}
          - { label: "Section Témoignages", name: "testimonials", widget: "object", fields: [
              { label: "Titre", name: "title", widget: "string" },
              { label: "Titre (partie surlignée)", name: "title_highlight", widget: "string" },
              { label: "Avis clients", name: "reviews", widget: "list", fields: [
                  { label: "Photo de l'auteur", name: "author_image", widget: "image" },
                  { label: "Texte alternatif de la photo", name: "author_alt", widget: "string" },
                  { label: "Citation", name: "quote", widget: "text" },
                  { label: "Infos de l'auteur (Nom, projet)", name: "author_info", widget: "string" }
                ]}
            ]}
          - { label: "Section FAQ", name: "faq", widget: "object", fields: [
              { label: "Titre", name: "title", widget: "string" },
              { label: "Titre (partie surlignée)", name: "title_highlight", widget: "string" },
              { label: "Questions & Réponses", name: "questions", widget: "list", fields: [
                  { label: "Question", name: "question", widget: "string" },
                  { label: "Réponse", name: "answer", widget: "markdown" }
                ]},
              { label: "Texte de conclusion", name: "outro_text", widget: "string" },
              { label: "Texte du bouton d'action", name: "cta_label", widget: "string" },
              { label: "Ancre du bouton", name: "cta_href", widget: "string" }
            ]}
          - { label: "Section Contact", name: "contact", widget: "object", fields: [
              { label: "Titre", name: "title", widget: "string" },
              { label: "Titre (partie surlignée)", name: "title_highlight", widget: "string" },
              { label: "Sous-titre", name: "subtitle", widget: "text" },
              { label: "Image portrait", name: "portrait_image", widget: "image" },
              { label: "Texte alternatif du portrait", name: "portrait_alt", widget: "string" },
              { label: "Nom", name: "name", widget: "string" },
              { label: "Titre de la session", name: "session_title", widget: "string" },
              { label: "Durée", name: "duration", widget: "string" },
              { label: "Méthode", name: "method", widget: "string" },
              { label: "Description", name: "description", widget: "text" },
              { label: "Titre du calendrier", name: "calendar_title", widget: "string" },
              { label: "Mois affiché (statique)", name: "calendar_month", widget: "string" },
              { label: "Jour sélectionné (statique)", name: "calendar_selected_day", widget: "string" },
              { label: "Créneaux horaires disponibles", name: "time_slots", widget: "list", fields: [
                  { label: "Heure (ex: 09:00)", name: "time", widget: "string" }
                ]}
            ]}
          - { label: "Pied de page (Footer)", name: "footer", widget: "object", fields: [
              { label: "Logo", name: "logo", widget: "image" },
              { label: "Texte alternatif du logo", name: "logo_alt", widget: "string" },
              { label: "Nom de la marque", name: "brand_name", widget: "string" },
              { label: "Description", name: "description", widget: "text" },
              { label: "Réseaux sociaux", name: "socials", widget: "list", fields: [
                  { label: "Plateforme (ex: Instagram)", name: "platform", widget: "string" },
                  { label: "URL du profil", name: "url", widget: "string" },
                  { label: "Icône (code SVG)", name: "icon_svg", widget: "text" }
                ]},
              { label: "Liens de navigation", name: "nav_links", widget: "list", fields: [
                  { label: "Texte", name: "label", widget: "string" },
                  { label: "Ancre", name: "href", widget: "string" }
                ]},
              { label: "Informations de contact", name: "contact_info", widget: "list", fields: [
                  { label: "Texte (ex: 06...)", name: "text", widget: "string" },
                  { label: "URL (ex: tel:+33...)", name: "url", widget: "string" }
                ]},
              { label: "Localisation", name: "location", widget: "string" },
              { label: "Texte du copyright", name: "copyright", widget: "string" }
            ]}
